# Generated by Django 4.1.7 on 2023-03-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_remove_favourite_user_delete_addcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ratings', models.FloatField()),
                ('feed', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='product',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='favourite',
        ),
    ]
