# Generated by Django 4.1.7 on 2023-03-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='review',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='review',
            name='positve',
        ),
    ]
