# Generated by Django 4.1.7 on 2023-03-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_review_negative_remove_review_neutral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('reviews', models.TextField(max_length=300)),
                ('overall', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
