# Generated by Django 4.1.7 on 2023-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_feedback_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.FloatField(),
        ),
    ]
