# Generated by Django 4.1.7 on 2023-03-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_feedback_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product_name',
            new_name='productname',
        ),
    ]
