# Generated by Django 4.1.7 on 2023-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_product_name_feedback_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='productname',
            field=models.CharField(max_length=100),
        ),
    ]
