# Generated by Django 4.1.7 on 2023-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_feedback_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('rate1', models.FloatField()),
                ('rate2', models.FloatField()),
                ('rate3', models.FloatField()),
                ('rate4', models.FloatField()),
            ],
        ),
    ]
