# Generated by Django 4.1.7 on 2023-04-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cat_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat_feedback',
            new_name='catfeedback',
        ),
    ]
