# Generated by Django 4.1.7 on 2023-04-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='socialmedia',
        ),
    ]
