# Generated by Django 4.1.7 on 2023-04-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateform', models.FloatField()),
                ('pagename', models.FloatField()),
                ('productname', models.FloatField()),
                ('review', models.FloatField()),
                ('ratings', models.FloatField()),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
