# Generated by Django 4.1.7 on 2023-04-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='pagename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='plateform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='productname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='review',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='sentiment',
            field=models.CharField(max_length=100),
        ),
    ]
