# Generated by Django 4.1.7 on 2023-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_social_pagename_alter_social_plateform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedcatogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('reviews', models.TextField(max_length=300)),
                ('productname', models.CharField(max_length=100)),
                ('catogory_name', models.CharField(max_length=100)),
                ('analysis', models.CharField(max_length=100)),
            ],
        ),
    ]
