# Generated by Django 4.2 on 2023-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_review_delete_catfeedback_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='neg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='neu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='pos',
            field=models.IntegerField(),
        ),
    ]
