# Generated by Django 4.2 on 2023-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_review_neg_alter_review_neu_alter_review_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='catogory_appear',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
        migrations.AddField(
            model_name='review',
            name='catogory_price',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
        migrations.AddField(
            model_name='review',
            name='catogory_qty',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
        migrations.AddField(
            model_name='review',
            name='catogory_service',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
        migrations.AlterField(
            model_name='review',
            name='neg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
